name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_update:
    runs-on: ubuntu-latest
    outputs:
      must-update: ${{ steps.check_version.outputs.must_update }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Check for new version
        id: check_version
        run: |
          git branch
          remote_date=$(date --utc +"%Y-%m-%d %H:%M:%S" -d "@$(curl -s https://aur.archlinux.org/rpc/v5/info/nodejs-nativefier | jq --raw-output '.results[0].LastModified')")
          local_date=$(date --utc +"%Y-%m-%d %H:%M:%S" -d "$(git log -1 --format=%cI PKGBUILD)")
          echo "Remote date: $remote_date"
          echo "Local date: $local_date"
          must_update=0
          if [[ "$remote_date" > "$local_date" ]] || [[ "$remote_date" == "$local_date" ]]; then must_update=1; fi
          echo "must_update=$must_update" >> $GITHUB_OUTPUT
#          echo "::set-output name=must-update::1"
      - name: Update PKGBUILD
        if: ${{ steps.check_version.outputs.must_update == 1 }}
        run: |
          NEW_RELEASE=$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")
          sed -i "s/^pkgver.*/pkgver=${NEW_RELEASE}/g" PKGBUILD
          sed -i "s/^pkgrel.*/pkgrel=1/g" PKGBUILD

      - name: Commit files
        id: commit
        if: ${{ steps.check_version.outputs.must_update == 1 }}
        run: |
          git config --local user.email "bakasura@protonmail.ch"
          git config --local user.name "bakasura"
          git commit -a -m "chore(deps): new version of nodejs-nativefier"
      - name: Push changes
        if: ${{ steps.check_version.outputs.must_update == 1 }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
  push-to-aur:
    needs: check_update
    if: ${{ needs.check_update.outputs.must-update == 1 }}
    uses: ./.github/workflows/main.yml
    secrets: inherit