name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
          fetch-depth: 0
      - name: Check for new version
        run: |
          remote_date=$(date --utc +"%Y-%m-%d %H:%M:%S" -d "@$(curl -s https://aur.archlinux.org/rpc/v5/info/nodejs-nativefier | jq --raw-output '.results[0].LastModified')")
          local_date=$(date --utc +"%Y-%m-%d %H:%M:%S" -d "$(git log -1 --format=%cI)")
          if [[ "$remote_date" > "$local_date" ]] || [[ "$remote_date" == "$date_local" ]]; then exit 1; else exit 0; fi
      - name: Update PKGBUILD
        if: failure()
        run: |
          NEW_RELEASE=$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")
          sed -i "s/^pkgver.*/pkgver=${NEW_RELEASE}/g" PKGBUILD
          sed -i "s/^pkgrel.*/pkgrel=1/g" PKGBUILD

      - name: Commit files
        run: |
          git commit -a -m "chore(deps): new version of nodejs-nativefier"
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git config --local user.name "github-actions[bot]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}