name: aur-publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@2.6.0
        with:
          pkgname: protonmail-nativefier
          pkgbuild: ./PKGBUILD
          commit_username: bakasura
          commit_email: bakasura@protonmail.ch
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          updpkgsums: 'true'
          assets: |
            multiaccount.patch
            protonmail-nativefier.desktop
            protonmail-nativefier.png
            protonmail-nativefier-2.desktop
            protonmail-nativefier-3.desktop
            protonmail-nativefier-4.desktop
            protonmail-nativefier-5.desktop